version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
      - orb-tools/pack
      - orb-tools/publish:
          context: dev
          requires: [orb-tools/pack]
          vcs-type: << pipeline.project.type >>
          orb-name: xavidop/circleci-orb-hello-world
          pub-type: dev


  publish-orb:
    when: << pipeline.git.tag >>
    jobs:
      - orb-tools/lint:
          filters: *filters
      - shellcheck/check:
          filters: *filters
          dir: ./src/scripts
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          context: dev
          vcs-type: << pipeline.project.type >>
          orb-name: xavidop/circleci-orb-hello-world
          pub-type: production
          requires:
            - orb-tools/pack
            - orb-tools/lint
            - shellcheck/check
          filters: *filters